typography_spectrum: 0.45424702763557434
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9335979535244405
  lightness: 0.8202759004198015
  saturation: 0.6658733892254531
  rhythmicContrast: 0.7362281808163971
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.023216439876705408
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Michael Fox
  email: MichaelFoxEmail@Gmail.com
  url: www.NewChannelMedia.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1b17b83d-0adb-41c1-86f1-08ef57e4ab52.png
name: New Channel Communications
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Michael Fox
description: Compelling Communicator
purpose: []
